name: Tata-Play
on:
 workflow_dispatch:
  inputs:
    git_token:
      description: 'Enter your GitHub Token'     
      required: true
    tata_mobile:
      description: 'Enter your Tata Sky Mobile Number'
      required: true
    sub_id:
      description: 'Enter your Tata Sky Subscriber ID'
      required: true
    tata_pass:
            description: 'Enter your Tata Sky Password'     
            required: true
    git_mail:
      description: 'Enter your GitHub Mail Address'
      required: true
    git_id:
      description: 'Enter your GitHub ID'
      required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Installing Dependencies
      continue-on-error: true
      run: |
            git config --global user.name "${{ github.event.inputs.git_id }}"
            git config --global user.email "${{ github.event.inputs.git_mail }}"
            git clone https://github.com/nik899/cooker
            cd cooker/code_samples/
            
            sudo apt install expect -y >> /dev/null 2>&1
            wget https://gist.githubusercontent.com/Nik899/aba45e911fd5ce6ca96804bed4cf4832/raw/post_script.exp
            wget https://raw.githubusercontent.com/ForceGT/Tata-Sky-IPTV/master/code_samples/main.py
            wget https://raw.githubusercontent.com/ForceGT/Tata-Sky-IPTV/master/code_samples/login.py
    
            chmod 755 *
            
            pass=$(echo '${{ github.event.inputs.tata_pass }}' | sed 's#\$#\\\\$#g' )
            
            
            sed -i 's/SUB_ID/${{ github.event.inputs.sub_id }}/g' post_script.exp
            sed -i 's/MOB_NO/${{ github.event.inputs.tata_mobile }}/g' post_script.exp
            sed -i 's/OTP/${{ github.event.inputs.tata_pass }}/g' post_script.exp
            
            ./post_script.exp >> /dev/null 2>&1
            
            touch mytoken.txt
            echo "${{ github.event.inputs.git_token }}" >> mytoken.txt
            gh auth login --with-token < mytoken.txt
            rm mytoken.txt
            cd ..
            touch allChannelPlaylist.m3u
            echo "Initial Test" >> allChannelPlaylist.m3u
            gh gist create allChannelPlaylist.m3u | tee gist_link.txt >> /dev/null 2>&1
            sed -i 's/gist/${{ github.event.inputs.git_token }}@gist/g' gist_link.txt
            gist_url=$(cat gist_link.txt)
            dir="${gist_url##*/}"
            rm allChannelPlaylist.m3u && rm gist_link.txt
            gh repo create MyTataSky --private -y || echo "New repo has been created"
            mkdir -p .github/workflows && cd .github/workflows
            wget https://https://gist.githubusercontent.com/sri012/8be52c7d2e3e393ffb387c2e689c827b/raw/SriTataDaily.yml >> /dev/null 2>&1
            wget https://gist.githubusercontent.com/sri012/9da633b25f52db260084f3b10ad4e45b/raw/substitute.txt >> /dev/null 2>&1
            export dir=$dir
            export gist_url=$gist_url
            export git_id=${{ github.event.inputs.git_id }}
            export git_token=${{ github.event.inputs.git_token }}
            export git_mail=${{ github.event.inputs.git_mail }}
            cat substitute.txt | envsubst >> TataSkyDailyWorkflow.yml
            rm substitute.txt
            cd ../..
            rm -rf .git
            cd ..
            git clone https://${{ github.event.inputs.git_token }}@github.com/${{ github.event.inputs.git_id }}/MyTataSky
            rm -rf MyTataSky/*
            rm -rf MyTataSky/.github
            mv cooker/* MyTataSky/
            mv cooker/.github MyTataSky/
            cd MyTataSky/
            git add .
            git commit --author="TechieSneh<techiesneh@gmail.com>" -m "Update Repo"
            git push
